require('dotenv').config();

module.exports = { 
	DB_HOST: process.env.DB_HOST,
	DB_USERNAME: process.env.DB_USERNAME,
	DB_PASSWORD: process.env.DB_PASSWORD,
	JWT_SECRET: process.env.APP_JWT_SECRET,
	MESSAGE_BROKER_URL: process.env.MESSAGE_BROKER_URL,
	AUTH_BINDING_KEY: process.env.AUTH_BINDING_KEY,
	EXCHANGE_NAME: process.env.EXCHANGE_NAME,
	AUTH_QUEUE_NAME: process.env.AUTH_QUEUE_NAME,
	AUTH_BINDING_REPLY_KEY: process.env.AUTH_BINDING_REPLY_KEY,
	EXCHANGE_REPLY_NAME: process.env.EXCHANGE_REPLY_NAME,
	AUTH_QUEUE_REPLY_NAME: process.env.AUTH_QUEUE_REPLY_NAME,
	//FS
	FS_SERVICE_BINDING_KEY: process.env.FS_SERVICE_BINDING_KEY,
	FS_SERVICE_QUEUE_NAME: process.env.FS_SERVICE_QUEUE_NAME,
	//FS
	CREATE_NEW_USER_BINDING_KEY: process.env.CREATE_NEW_USER_BINDING_KEY,
	CREATE_NEW_USER_QUEUE_NAME: process.env.CREATE_NEW_USER_QUEUE_NAME,
	// CHECK_ROLE
	CHECK_ROLE_BINDING_KEY: process.env.CHECK_ROLE_BINDING_KEY,
	CHECK_ROLE_QUEUE: process.env.CHECK_ROLE_QUEUE,
	
	//EXCHANGES
	AUTH_EXCHANGE_NAME: process.env.AUTH_EXCHANGE_NAME,
	FS_EXCHANGE_NAME: process.env.FS_EXCHANGE_NAME,

	//AUTH BINDING_KEYS
	AUTH_LOGIN_BINDING_KEY: process.env.AUTH_LOGIN_BINDING_KEY,
	AUTH_REGISTER_BINDING_KEY: process.env.AUTH_REGISTER_BINDING_KEY,
	AUTH_CHECK_ROLE_BINDING_KEY: process.env.AUTH_CHECK_ROLE_BINDING_KEY,

	// AUTH QUEUE_NAMES
	AUTH_LOGIN_QUEUE_NAME: process.env.AUTH_LOGIN_QUEUE_NAME,
	AUTH_REGISTER_QUEUE_NAME: process.env.AUTH_REGISTER_QUEUE_NAME,
	AUTH_CHECK_ROLE_QUEUE_NAME: process.env.AUTH_CHECK_ROLE_QUEUE_NAME,

	//FS BINDING_KEYS
	FS_CREATE_NEW_USER_BINDING_KEY: process.env.FS_CREATE_NEW_USER_BINDING_KEY,
	FS_INIT_BINDING_KEY: process.env.FS_INIT_BINDING_KEY,

	// FS QUEUE_NAMES
	FS_CREATE_NEW_USER_QUEUE_NAME: process.env.FS_CREATE_NEW_USER_QUEUE_NAME,
	FS_INIT_QUEUE_NAME: process.env.FS_INIT_QUEUE_NAME
	
};
